# Generated by Django 2.1.4 on 2019-03-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebration_resources', models.CharField(max_length=255)),
                ('celebration_volunteers', models.CharField(max_length=255)),
                ('celebration_attendees', models.CharField(max_length=255)),
                ('celebration_events', models.CharField(max_length=255)),
                ('celebration_eventdate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'celebration',
            },
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.DeleteModel(
            name='Celebrations',
        ),
    ]
