# Generated by Django 2.1.4 on 2019-03-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190306_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Celebration',
            new_name='CommunityEvents',
        ),
        migrations.RenameField(
            model_name='communityevents',
            old_name='celebration_events',
            new_name='communityevents_attendees',
        ),
        migrations.RenameField(
            model_name='communityevents',
            old_name='celebration_eventdate',
            new_name='communityevents_eventdate',
        ),
        migrations.RenameField(
            model_name='communityevents',
            old_name='celebration_attendees',
            new_name='communityevents_events',
        ),
        migrations.RenameField(
            model_name='communityevents',
            old_name='celebration_resources',
            new_name='communityevents_resources',
        ),
        migrations.RenameField(
            model_name='communityevents',
            old_name='celebration_volunteers',
            new_name='communityevents_volunteers',
        ),
        migrations.AlterModelTable(
            name='communityevents',
            table='communityevents',
        ),
    ]
