# Generated by Django 2.1.4 on 2019-01-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingminutes',
            name='meetmintext',
            field=models.TextField(),
        ),
    ]
