# Generated by Django 2.1.4 on 2019-01-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20190127_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingminutes',
            name='meetmintext',
        ),
    ]
