# Generated by Django 2.1.4 on 2019-01-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_remove_meetingminutes_meetmintext'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminutes',
            name='meetmintext',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
