# Generated by Django 2.1.4 on 2019-01-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20190127_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingminutes',
            name='meetmintext',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
