# Generated by Django 2.1.4 on 2019-02-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_meeting_meetingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meetingid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
