# Generated by Django 2.1.4 on 2019-02-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_auto_20190213_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meetingid',
        ),
    ]
