# Generated by Django 2.1.4 on 2019-02-13 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_remove_meeting_meetingid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingminutes',
            old_name='meetminid',
            new_name='meetingminutesid',
        ),
    ]
